### ISSUE TITLE
Convert CircleCI Scaffold From 1.0 to 2.0

### ISSUE THREAD

**Issue by felicianotech** [wp-cli/scaffold-command#52]
The scaffold generated when CircleCI is chosen is a CircleCI 1.0 config file. Can this be updated for CircleCI 2.0? I'm a Developer Evangelist over at CircleCI and I can assist if needed.

Thanks.

**Comment by miya0001** [comment]
Thanks @felicianotech 

I will try to submit a pull-request for it.
if I have something problem, please help. :)

**Comment by miya0001** [comment]
Hi!

I need help!

* Docker images doesn't have mysql server, should we install mysql into the container or should we use docker compose or so?
* How do we run tests on multiple PHP version? Docker image doesn't have phpenv.
* We can choose `machine` which isn't docker image, but it doesn't have `phpenv` and `composer`.

**Comment by JPry** [comment]
@miya0001 I haven't used  CircleCI 2.0 yet, but is it possible to define multiple images? Maybe something like this:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6
      - image: circleci/php:7.0
      - image: circleci/php:7.1
```
