### ISSUE TITLE
Gitlab CI tests lacks tests for different WP versions

### ISSUE THREAD

**Issue by nextgenthemes** [wp-cli/scaffold-command#69]
Or am I missing something?

I am used to travis where you can define several WP versions for the tests.

I am new to docker but I have a fair knowlege about Linux and Ubuntu.

One way that could be done is by actually just cleaning the /temp folder and installing the tests again with a different WP version. This way not a complete new docker bootup would be needed. Nut sure if that is a good way.

Like this. Assuming the config that wp-cli currently adds. **Untested**

```
PHPunit:PHP5.3:MySQL:
  image: tetraweb/php:5.3
  services:
    - mysql:5.6
  script:
  - phpcs
  - phpunit
  - rm -rf /tmp/*
  - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql nightly true
  - phpcs
  - phpunit
```
