### ISSUE TITLE
Add Support for Bitbucket Pipelines to --ci

### ISSUE THREAD

**Issue by jgraup** [wp-cli/scaffold-command#9]
Any thoughts on adding support for [Bitbucket Pipelines](https://bitbucket.org/product/features/pipelines) to `[--ci=<provider>]`?  
* https://bitbucket.org/product/features/pipelines
* https://www.cuttlesoft.com/bitbucket-pipelines-first-impression/
* https://bitbucket.org/rw_grim/local-pipelines/overview

---

*bitbucket-pipelines.yml*
```yml
# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: phpunit/phpunit:5.0.3
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer install
```

**Comment by danielbachhuber** [comment]
I'm open to it if you'd like to submit a pull request for it. Bitbucket is a large enough provider.

**Comment by jgraup** [comment]
Thanks. I'll try to get to it this week.

**Comment by danielbachhuber** [comment]
Closing this as `maybelater`, pending someone's motivation to submit and maintain a config file.

**Comment by tfirdaus** [comment]
Hi, @danielbachhuber 👋

Are you still open to adding support for Bitbucket Pipelines? I've created [wp-docklines](https://github.com/tfirdaus/wp-docklines) that I've been using for some time now to perform CI/CD with Bitbucket Pipelines as well as for localhost environment in [wp-locker](https://github.com/tfirdaus/wp-locker).

Here is an example of how the `bitbucket-pipelines.yml` configuration might look like in its simplest form:

```yml
pipelines:
  default:
    - step:
        name: "PHP 7.0"
        image: tfirdaus/wp-docklines:php7.0-fpm
        caches:
          - wp-core
        script:
          - bash bin/install-wp-tests.sh wp_test wp wp 127.0.0.1 latest true
          - phpunit
        services:
          - database

definitions:
  caches:
    wp-core: /tmp/wordpress

  services:
    database:
      image: mysql:5.5
      environment:
        MYSQL_DATABASE: 'wp_test'
        MYSQL_USER: 'wp'
        MYSQL_PASSWORD: 'wp'
        MYSQL_ROOT_PASSWORD: 'root'
```
